# Global Nginx FastCGI Cache Configuration
# This file is usually placed in /etc/nginx/conf.d/soto-cache.conf

fastcgi_cache_path /var/cache/nginx/sotocache levels=1:2 keys_zone=SOTOCACHE:100m max_size=1G inactive=60m use_temp_path=off;
fastcgi_cache_key "$scheme$request_method$host$request_uri";
fastcgi_ignore_headers Cache-Control Expires Set-Cookie;
